!Command
positional: []
named: []
command:
- plantcv-workflow.py
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "Traceback (most recent call last):\n  File \"/tmp/tmpwh923u31/bin/plantcv-workflow.py\"\
  , line 8, in <module>\n    import plantcv.parallel as pcvp\n  File \"/tmp/tmpwh923u31/lib/python3.7/site-packages/plantcv/parallel/__init__.py\"\
  , line 6, in <module>\n    from plantcv.parallel.process_results import process_results\n\
  \  File \"/tmp/tmpwh923u31/lib/python3.7/site-packages/plantcv/parallel/process_results.py\"\
  , line 4, in <module>\n    from plantcv.plantcv import fatal_error\n  File \"/tmp/tmpwh923u31/lib/python3.7/site-packages/plantcv/plantcv/__init__.py\"\
  , line 137, in <module>\n    from plantcv.plantcv.print_image import print_image\n\
  \  File \"/tmp/tmpwh923u31/lib/python3.7/site-packages/plantcv/plantcv/print_image.py\"\
  , line 3, in <module>\n    import cv2\nImportError: libGL.so.1: cannot open shared\
  \ object file: No such file or directory\n"
generated_using:
- --help
