!Command
command:
- fc_contig_annotate
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "falcon-kit 1.8.1 (pip thinks \"falcon-kit 1.8.1\")\npypeflow 2.3.0\nTraceback\
  \ (most recent call last):\n  File \"/usr/local/bin/fc_contig_annotate\", line 11,\
  \ in <module>\n    load_entry_point('falcon-kit==1.8.1', 'console_scripts', 'fc_contig_annotate')()\n\
  \  File \"/usr/local/lib/python3.7/site-packages/falcon_kit/mains/contig_annotate.py\"\
  , line 9, in main\n    G_asm = AsmGraph(\"sg_edges_list\", \"utg_data\", \"ctg_paths\"\
  )\n  File \"/usr/local/lib/python3.7/site-packages/falcon_kit/fc_asm_graph.py\"\
  , line 25, in __init__\n    self.load_sg_data(sg_file)\n  File \"/usr/local/lib/python3.7/site-packages/falcon_kit/fc_asm_graph.py\"\
  , line 32, in load_sg_data\n    counter = FilePercenter(sg_file)\n  File \"/usr/local/lib/python3.7/site-packages/falcon_kit/io.py\"\
  , line 76, in FilePercenter\n    size = filesize(fn)\n  File \"/usr/local/lib/python3.7/site-packages/pypeflow/io.py\"\
  , line 114, in filesize\n    return os.stat(fn).st_size\nFileNotFoundError: [Errno\
  \ 2] No such file or directory: 'sg_edges_list'\n"
generated_using:
- --help
