!Command
command:
- random_forest.py
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "Traceback (most recent call last):\n  File \"/usr/local/bin/random_forest.py\"\
  , line 32, in <module>\n    from secimtools.visualManager.module_bar import quickHBar\n\
  \  File \"/usr/local/lib/python2.7/site-packages/secimtools/visualManager/module_bar.py\"\
  , line 14, in <module>\n    import matplotlib.pyplot as plt\n  File \"/usr/local/lib/python2.7/site-packages/matplotlib/pyplot.py\"\
  , line 114, in <module>\n    _backend_mod, new_figure_manager, draw_if_interactive,\
  \ _show = pylab_setup()\n  File \"/usr/local/lib/python2.7/site-packages/matplotlib/backends/__init__.py\"\
  , line 32, in pylab_setup\n    globals(),locals(),[backend_name],0)\n  File \"/usr/local/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py\"\
  , line 18, in <module>\n    from .backend_qt5agg import FigureCanvasQTAggBase as\
  \ _FigureCanvasQTAggBase\n  File \"/usr/local/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py\"\
  , line 16, in <module>\n    from .backend_qt5 import QtCore\n  File \"/usr/local/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py\"\
  , line 31, in <module>\n    from .qt_compat import QtCore, QtGui, QtWidgets, _getSaveFileName,\
  \ __version__\n  File \"/usr/local/lib/python2.7/site-packages/matplotlib/backends/qt_compat.py\"\
  , line 137, in <module>\n    from PyQt4 import QtCore, QtGui\nImportError: libXext.so.6:\
  \ cannot open shared object file: No such file or directory\n"
generated_using:
- --help
