!Command
command:
- arvados-cwl-runner
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "Traceback (most recent call last):\n  File \"/usr/local/bin/arvados-cwl-runner\"\
  , line 10, in <module>\n    sys.exit(main(sys.argv[1:], sys.stdout, sys.stderr))\n\
  \  File \"/usr/local/lib/python3.8/site-packages/arvados_cwl/__init__.py\", line\
  \ 285, in main\n    parser = arg_parser()\n  File \"/usr/local/lib/python3.8/site-packages/arvados_cwl/__init__.py\"\
  , line 121, in arg_parser\n    exgroup.add_argument(\"--version\", action=\"version\"\
  , help=\"Print version and exit\", version=versionstring())\n  File \"/usr/local/lib/python3.8/site-packages/arvados_cwl/__init__.py\"\
  , line 96, in versionstring\n    arvcwlpkg = pkg_resources.require(\"arvados-cwl-runner\"\
  )\n  File \"/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py\",\
  \ line 899, in require\n    needed = self.resolve(parse_requirements(requirements))\n\
  \  File \"/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py\", line\
  \ 785, in resolve\n    raise DistributionNotFound(req, requirers)\npkg_resources.DistributionNotFound:\
  \ The 'typing>=3.6.4' distribution was not found and is required by arvados-cwl-runner\n"
generated_using:
- --help
docker_image: quay.io/biocontainers/arvados-cwl-runner:2.0.4--pyh864c0ab_0
