!Command
command:
- computeOrderedMatrix
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "Traceback (most recent call last):\n  File \"/usr/local/bin/computeOrderedMatrix\"\
  , line 6, in <module>\n    from ultraheatmap.computeOrderedMatrix import main\n\
  \  File \"/usr/local/lib/python3.6/site-packages/ultraheatmap/computeOrderedMatrix.py\"\
  , line 8, in <module>\n    import ultraheatmap.computeMatrix as cm\n  File \"/usr/local/lib/python3.6/site-packages/ultraheatmap/computeMatrix.py\"\
  , line 6, in <module>\n    from deeptools.heatmapper import heatmapper\n  File \"\
  /usr/local/lib/python3.6/site-packages/deeptools/heatmapper.py\", line 8, in <module>\n\
  \    from deeptools import getScorePerBigWigBin\n  File \"/usr/local/lib/python3.6/site-packages/deeptools/getScorePerBigWigBin.py\"\
  , line 10, in <module>\n    import deeptools.utilities\n  File \"/usr/local/lib/python3.6/site-packages/deeptools/utilities.py\"\
  , line 4, in <module>\n    from deeptools.bamHandler import openBam\n  File \"/usr/local/lib/python3.6/site-packages/deeptools/bamHandler.py\"\
  , line 2, in <module>\n    import pysam\n  File \"/usr/local/lib/python3.6/site-packages/pysam/__init__.py\"\
  , line 5, in <module>\n    from pysam.libchtslib import *\nImportError: libcrypto.so.1.0.0:\
  \ cannot open shared object file: No such file or directory\n"
generated_using:
- --help
docker_image: quay.io/biocontainers/ultraheatmap:1.3.1--pyh3252c3a_0
