!Command
positional: []
named: []
command:
- call-program
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "Traceback (most recent call last):\n  File \"/tmp/tmphhb7ctl3/bin/call-program\"\
  , line 6, in <module>\n    from pkg_resources import load_entry_point\n  File \"\
  /tmp/tmphhb7ctl3/lib/python3.6/site-packages/pkg_resources/__init__.py\", line 3260,\
  \ in <module>\n    @_call_aside\n  File \"/tmp/tmphhb7ctl3/lib/python3.6/site-packages/pkg_resources/__init__.py\"\
  , line 3244, in _call_aside\n    f(*args, **kwargs)\n  File \"/tmp/tmphhb7ctl3/lib/python3.6/site-packages/pkg_resources/__init__.py\"\
  , line 3273, in _initialize_master_working_set\n    working_set = WorkingSet._build_master()\n\
  \  File \"/tmp/tmphhb7ctl3/lib/python3.6/site-packages/pkg_resources/__init__.py\"\
  , line 583, in _build_master\n    ws.require(__requires__)\n  File \"/tmp/tmphhb7ctl3/lib/python3.6/site-packages/pkg_resources/__init__.py\"\
  , line 900, in require\n    needed = self.resolve(parse_requirements(requirements))\n\
  \  File \"/tmp/tmphhb7ctl3/lib/python3.6/site-packages/pkg_resources/__init__.py\"\
  , line 786, in resolve\n    raise DistributionNotFound(req, requirers)\npkg_resources.DistributionNotFound:\
  \ The 'spur' distribution was not found and is required by misc\n"
generated_using:
- --help
