!Command
command:
- rename_fasta_seqID.py
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "Traceback (most recent call last):\n  File \"/usr/local/bin/rename_fasta_seqID.py\"\
  , line 24, in <module>\n    fout = open(sys.argv[3], 'w')\nIndexError: list index\
  \ out of range\n"
generated_using:
- --help
docker_image: quay.io/biocontainers/mitofinder:1.4--py27h516909a_0
