!Command
positional: []
named: []
command:
- sqt
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "Traceback (most recent call last):\n  File \"/tmp/tmpfzph3bbu/lib/python3.6/site-packages/pkg_resources/__init__.py\"\
  , line 583, in _build_master\n    ws.require(__requires__)\n  File \"/tmp/tmpfzph3bbu/lib/python3.6/site-packages/pkg_resources/__init__.py\"\
  , line 900, in require\n    needed = self.resolve(parse_requirements(requirements))\n\
  \  File \"/tmp/tmpfzph3bbu/lib/python3.6/site-packages/pkg_resources/__init__.py\"\
  , line 791, in resolve\n    raise VersionConflict(dist, req).with_context(dependent_req)\n\
  pkg_resources.ContextualVersionConflict: (xopen 0.7.3 (/tmp/tmpfzph3bbu/lib/python3.6/site-packages),\
  \ Requirement.parse('xopen~=0.8.4'), {'cutadapt'})\n\nDuring handling of the above\
  \ exception, another exception occurred:\n\nTraceback (most recent call last):\n\
  \  File \"/tmp/tmpfzph3bbu/bin/sqt\", line 6, in <module>\n    from pkg_resources\
  \ import load_entry_point\n  File \"/tmp/tmpfzph3bbu/lib/python3.6/site-packages/pkg_resources/__init__.py\"\
  , line 3260, in <module>\n    @_call_aside\n  File \"/tmp/tmpfzph3bbu/lib/python3.6/site-packages/pkg_resources/__init__.py\"\
  , line 3244, in _call_aside\n    f(*args, **kwargs)\n  File \"/tmp/tmpfzph3bbu/lib/python3.6/site-packages/pkg_resources/__init__.py\"\
  , line 3273, in _initialize_master_working_set\n    working_set = WorkingSet._build_master()\n\
  \  File \"/tmp/tmpfzph3bbu/lib/python3.6/site-packages/pkg_resources/__init__.py\"\
  , line 585, in _build_master\n    return cls._build_from_requirements(__requires__)\n\
  \  File \"/tmp/tmpfzph3bbu/lib/python3.6/site-packages/pkg_resources/__init__.py\"\
  , line 598, in _build_from_requirements\n    dists = ws.resolve(reqs, Environment())\n\
  \  File \"/tmp/tmpfzph3bbu/lib/python3.6/site-packages/pkg_resources/__init__.py\"\
  , line 791, in resolve\n    raise VersionConflict(dist, req).with_context(dependent_req)\n\
  pkg_resources.ContextualVersionConflict: (xopen 0.7.3 (/tmp/tmpfzph3bbu/lib/python3.6/site-packages),\
  \ Requirement.parse('xopen~=0.8.4'), {'cutadapt'})\n"
generated_using:
- --help
