!Command
command:
- nosetests-2.7
positional:
- !Positional
  description: File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py",
    line 3079, in _call_aside
  position: 0
  name: '@_call_aside'
  optional: false
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "Traceback (most recent call last):\n  File \"/usr/local/bin/nosetests-2.7\"\
  , line 6, in <module>\n    from pkg_resources import load_entry_point\n  File \"\
  /usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py\", line 3095, in\
  \ <module>\n    @_call_aside\n  File \"/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py\"\
  , line 3079, in _call_aside\n    f(*args, **kwargs)\n  File \"/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py\"\
  , line 3108, in _initialize_master_working_set\n    working_set = WorkingSet._build_master()\n\
  \  File \"/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py\", line\
  \ 570, in _build_master\n    ws.require(__requires__)\n  File \"/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py\"\
  , line 888, in require\n    needed = self.resolve(parse_requirements(requirements))\n\
  \  File \"/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py\", line\
  \ 774, in resolve\n    raise DistributionNotFound(req, requirers)\npkg_resources.DistributionNotFound:\
  \ The 'nose==1.3.7' distribution was not found and is required by the application\n"
generated_using:
- --help
